// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AddressToUsername, AddressToUsernameTableId } from "./tables/AddressToUsername.sol";
import { UserIndexToUsername, UserIndexToUsernameTableId } from "./tables/UserIndexToUsername.sol";
import { StateJokes, StateJokesTableId } from "./tables/StateJokes.sol";
import { GameMetadata, GameMetadataData, GameMetadataTableId } from "./tables/GameMetadata.sol";
import { GameCursor, GameCursorTableId } from "./tables/GameCursor.sol";
import { IsPlayerValid, IsPlayerValidData, IsPlayerValidTableId } from "./tables/IsPlayerValid.sol";
import { IsVoted, IsVotedTableId } from "./tables/IsVoted.sol";
import { RoundInfo, RoundInfoData, RoundInfoTableId } from "./tables/RoundInfo.sol";
import { Responses, ResponsesData, ResponsesTableId } from "./tables/Responses.sol";
import { ScoreBoard, ScoreBoardData, ScoreBoardTableId } from "./tables/ScoreBoard.sol";
import { JokeUsage, JokeUsageData, JokeUsageTableId } from "./tables/JokeUsage.sol";
