// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAnswerSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAnswerSystem {
  error AnswerSystem__WrongState();
  error AnswerSystem__AlreadyReplied();
  error AnswerSystem__NotAuthorized();

  function submitAnswer(uint256 gameID, string memory answer) external;
}
