// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameInitSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameInitSystem {
  error GameInitSystem__GameAlreadyInitialized();

  function initGame(uint32 limitRound, uint32 limit) external returns (uint256);
}
