// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSystem {
  error GameSystem__GameNotInWaitingState();
  error GameSystem__GameIsNotFull();
  error GameSystem__WrongState();

  function moveFromGeneratingToTyping(uint256 gameID) external;

  function moveFromTypingToVoting(uint256 gameID) external;

  function moveFromVotingToNextStage(uint256 gameID) external;

  function claimWinner(uint256 gameID) external;
}
