// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IJokeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IJokeSystem {
  error JokeSystem__RoundShouldBeMore();
  error JokeSystem__NoAuthorization();
  error JokeSystem__NoFriendFire();
  error JokeSystem__WrongToIndex();

  function createFrontEndOnlyJoke(
    uint256 gameID,
    uint32 roundNum,
    uint256 toUserIndex,
    uint256 fromUserIndex,
    uint32 jokeIndex
  ) external;

  function createStateJoke(
    uint256 gameID,
    uint32 roundNum,
    uint256 toUserIndex,
    uint256 fromUserIndex,
    uint32 jokeIndex
  ) external;
}
