// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IVoteSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVoteSystem {
  error VoteSystem__WrongState();
  error VoteSystem__NotAuthorized();
  error VoteSystem__AlreadyVoted();
  error VoteSystem__CannotVoteForSelf();

  function vote(uint256 gameID, uint256 color) external;
}
