// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IAnswerSystem } from "./IAnswerSystem.sol";
import { IGameInitSystem } from "./IGameInitSystem.sol";
import { IGameSystem } from "./IGameSystem.sol";
import { IIdentitySystem } from "./IIdentitySystem.sol";
import { IJokeSystem } from "./IJokeSystem.sol";
import { INFTSystem } from "./INFTSystem.sol";
import { IVoteSystem } from "./IVoteSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAnswerSystem,
  IGameInitSystem,
  IGameSystem,
  IIdentitySystem,
  IJokeSystem,
  INFTSystem,
  IVoteSystem
{

}
